config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get 'application/index', as: 'home'


  # GET /drinks     => drinks controller's index action
  get 'drinks', to: 'drinks#index', as: 'drinks'

  # GET /drinks/:id => drinks controller's show action
  get 'drinks/:id', to: 'drinks#show', as: 'drink', id: /\d+/

  # GET /drinks/new => drinks controller's new action
  get 'drinks/new', to: 'drinks#new', as: 'new_drink'

  # POST /drinks    => drinks controller's create action
  post 'drinks', to: 'drinks#create'

  # DELETE /drinks/:id => drinks controller's delete action
  delete 'drinks/:id', to: 'drinks#destroy', as: 'delete_drink'

  


  #####################


  # GET /cocktails     => cocktails controller's index action
  get 'cocktails', to: 'cocktails#index', as: 'cocktails'

  # GET /cocktails/:id => cocktails controller's show action
  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail', id: /\d+/


  # GET /cocktails/:id/drinks => cocktails controller's show drinks action
  get 'cocktails/:id/drinks', to: 'cocktails#showdrinks', as: 'cocktail_drinks', id: /\d+/

  

  # GET /cocktails/new => cocktails controller's new action
  get 'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'

  # POST /cocktails    => cocktails controller's create action
  post 'cocktails', to: 'cocktails#create', as: 'create_cocktail'

  # DELETE /cocktails/:id => cocktails controller's delete action
  delete 'cocktails/:id', to: 'cocktails#destroy', as: 'delete_cocktail'






  #####################
    # GET /drinks_cocktails/new => cocktails controller's new action
    get 'drinks_cocktails/new', to: 'drinks_cocktails#new', as: 'new_drinks_cocktail'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    #attr_accessible :drinks_cocktails_attributes
    validates :name, presence: true

    has_many :drinks_cocktails, dependent: :destroy
    has_many :drinks, through: :drinks_cocktails

    accepts_nested_attributes_for :drinks_cocktails, allow_destroy: true, reject_if: :all_blank
end

app/models/drink.rb
class Drink < ApplicationRecord
    validates :name, :quantity, presence: true
    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0}

    has_many :drinks_cocktails
    has_many :cocktails, through: :drinks_cocktails
end

app/models/drinks_cocktail.rb
class DrinksCocktail < ApplicationRecord
    validates :drink_id, :quantity, presence: true
    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1}

    belongs_to :cocktail, optional: true
    belongs_to :drink
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index

    end

    def drinks
        
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

    def index
        @cocktails = Cocktail.all
    end

    def show
        @cocktail = Cocktail.find(params[:id])
        @drinks = @cocktail.drinks
        @helper = DrinksCocktail.where cocktail_id: @cocktail.id
        @info = {}
        @drinks.each do |drink|
            aux = @helper.where drink_id: drink.id
            quant = aux.pluck :quantity
            @info[drink.name] = quant
        end
    end

    def new
        @cocktail = Cocktail.new
        @cocktail.drinks_cocktails.build
    end

    def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    def destroy
        @cocktail = Cocktail.find(params[:id])
        @cocktail.destroy
        redirect_to cocktails_path, notice => "cocktail has been deleted"
    end

    def update
        @cocktail = Cocktail.find(params[:id])
        if @cocktail.update_Attributes(cocktail_params)
            redirect_to cocktail_path(@cocktail)
        end
    end

    private
        def cocktail_params
            params.require(:cocktail).permit(:name, drinks_cocktails_attributes: DrinksCocktail.attribute_names.map(&:to_sym).push(:_destroy))
        end

        def set_cocktail
            @cocktail = Cocktail.find(params[:id])
        end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

    def index
        @drinks = Drink.all
    end

    def show
        @drink = Drink.find(params[:id])
    end

    def new
        @drink = Drink.new
    end

    def create
        @drink = Drink.new(drink_params)
        if @drink.save
            redirect_to drink_path(@drink)
        else
            render :new
        end
    end

    def destroy
        @drink = Drink.find(params[:id])
        @drink.destroy
        redirect_to drinks_path, notice => "Drink has been deleted"
    end

    def update
        @drink = Drink.find(params[:id])
        if @drink.update_Attributes(drink_params)
            redirect_to drink_path(@drink)
        end
    end

    private

    def drink_params
        params.require(:drink).permit(:name, :quantity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/application/index.html.erb
<h2>
    <%= link_to("Drinks",
    {:controller => 'drinks', 
    :action => 'index'}) %>
</h2>
<br/>
<h2>
    <%= link_to("Cocktails",
    {:controller => 'cocktails', 
    :action => 'index'}) %>
</h2>

app/views/cocktails/_drinks_cocktails_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
    <%= f.label :drink_id %>
    <%= f.text_field :drink_id%>
    <%= f.label :quantity %>
    <%= f.text_field :quantity%>
    <button type="button" data-action="nested-form#remove">Remove Drink</button>
    <%= f.hidden_field :_destroy %>
</div>

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, data: {
    controller: "nested-form",
    nested_form_wrapper_selector_value: '.nested-form-wrapper'
}) do |form| %>
    <% if cocktail.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(project.errors.count, "error") %> prohibited this cocktail because: </h2>
            <ul>
                <% project.errors.each do |error| %>
                    <li><%= error.full_message%></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
    </div>
    <%###############################################  %>
    <template data-nested-form-target="template">
        <%form.fields_for :drinks_cocktails, DrinksCocktail.new, child_index: " NEW_RECORD" do |drinks_cocktails_fields| %>
            <%= render "drinks_cocktails_form", f: drinks_cocktails_fields %>
        <% end %>
    </template>
    <%= form.fields_for :drinks_cocktails do |drinks_cocktails_fields| %>
        <%= render "drinks_cocktails_form", f: drinks_cocktails_fields %>
    <% end %>
    <div data-nested-form-target="target"></div>
    <button type="button" data-action=>Add Drink</button> 
    <%############################## #################  %>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/cocktails/index.html.erb
<h2><%= link_to 'Add New Cocktail', new_cocktail_path %></h2>

<br/>
<br/>

<% @cocktails.each do |cocktail| %>
    <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
<% end %>

app/views/cocktails/new.html.erb
<h2>Add a Cocktail</h2>

<%= render "form", cocktail: @cocktail %>

app/views/cocktails/new3.html.erb
<h2>Add a Cocktail</h2>

<%= simple_form_for(@cocktail) do |f| %>
    <% if @cocktail.errors.any? %>
        <h3><%= pluralize(@cocktail.errors.size, 'error') %> prevented this cocktail from being saved</h3>
        <ul>
            <% @cocktail.errors.full_messages.each do |msg| %>
                <li> <h4><%= msg %></h4> </li>
            <% end %>
        </ul>
    <% end %>
    <%= f.input :name %>
    <br/>
    <h3>Bebidas</h3>
    <div id="drinks_cocktails">
        <%= f.simple_fields_for :drinks_cocktails do |builder| %>
            <%= render 'drinks_cocktail_fields', f: builder %>
        <% end %>
        <div class="links">
            <%= link_to_add_association 'Add Drink', f, :drinks_cocktails %>
        </div>
    </div>
    <div class="form-actions">
        <%= f.submit %>
    </div>
    <br/>
<% end %>

app/views/cocktails/show.html.erb
<%= turbo_frame_tag "cocktail" do %>
    <h2><%= @cocktail.name %></h2>
    <% @info.each do |inf| %>
        <h3><%= inf[0] %> : <%= inf[1][0] %></h3>
    <% end %>
<% end %>

app/views/drinks/_drink.html.erb
<div id="<%= dom_id drink %>">
  <p>
    <strong>Name:</strong>
    <%= drink.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= drink.quantity %>
  </p>

</div>

app/views/drinks/_form.html.erb
<%= simple_form_for(@drink) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render "form", drink: @drink %>

<br>

<div>
  <%= link_to "Show this drink", @drink %> |
  <%= link_to "Back to drinks", drinks_path %>
</div>

app/views/drinks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Drinks</h1>

<div id="drinks">
  <% @drinks.each do |drink| %>
    <%= render drink %>
    <p>
      <%= link_to "Show this drink", drink %>
    </p>
  <% end %>
</div>

<%= link_to "New drink", new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render "form", drink: @drink %>

<br>

<div>
  <%= link_to "Back to drinks", drinks_path %>
</div>

app/views/drinks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @drink %>

<div>
  <%= link_to "Edit this drink", edit_drink_path(@drink) %> |
  <%= link_to "Back to drinks", drinks_path %>

  <%= button_to "Destroy this drink", @drink, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoelasRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <h1><%= link_to 'Moelas Bar',home_path %></h1>
    <br/>
    <br/>
    <%= yield %>
  </body>
</html>